# Generated by Django 6.0.1 on 2026-01-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
